services:
  mariadb:
    container_name: mariadb_inception
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

#  wordpress:
#    container_name: wp_inception
#    build: ./requirements/wordpress/.
#    depends_on:
#      - mariadb
#    volumes:
#      - wordpress:var/www/html
#    env_file:
#      - .env
#    networks:
#       - inception
#    restart: always
#
#  nginx:
#    container_name: nginx
#    build: ./requirements/nginx/.
#    ports:
#      - "443:443"
#    depends_on:
#      - wordpress
#    volumes:
#      -wordpress:/var/www/html
#    network:
#      - inception
#    restart: always

networks:
  inception:
    name: inception

volumes:
        wordpress:
                 name: wordpress
                 driver: local
                 driver_opts:
                         device: /home/tpicchio/data/wordpress
                         o: bind
                         type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                         device: /home/tpicchio/data/mariadb
                         o: bind
                         type: none
