version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - ./requirements/bonus/static_website:/var/www/static/
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always
  
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
      - wp-plugins:/var/www/wp-content/plugins
    networks:
      - inception
    restart: always

  redis:
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always
  
  vsftpd:
    build:
      context: .
      dockerfile: requirements/bonus/vsftpd/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    image: vsftpd
    container_name: vsftpd
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  adminer:
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  portainer:
    build:
      context: .
      dockerfile: requirements/bonus/portainer/Dockerfile
    image: portainer
    container_name: portainer
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  wp-volume:
    name: wp-volume
    driver_opts:
      o: bind
      type: none
      device: /home/tpicchio/data/wordpress
  
  wp-plugins:
    name: wp-plugins
    driver_opts:
      o: bind
      type: none
      device: /home/tpicchio/data/wordpress/wp-content/plugins

  db-volume:
    name: db-volume
    driver_opts:
      o: bind
      type: none
      device: /home/tpicchio/data/mariadb
  
  portainer_data:
    name: portainer_data
    driver_opts:
      o: bind
      type: none
      device: /home/tpicchio/data/portainer

networks:
  inception:
    driver: bridge
